
library(randomForest)
library(fields)
source("lambdahat_code.R") ## includes the gethypertv function for the basic confusion table bound
load("reanalysis/climatedata.rda") ## loads 'data', the object generated by your pre-processing

source("Climate/climate-preprocessing.R")

data <- list()
data$air <- air
data$prate <- prate
data$shum <- shum
data$mslp <- mslp
## what is missing
## 1) gethyper was lacking the adjustment witnesses->TV bound, so gets worse
## 2) or one leaves gethyper and gets a bound for witnesses instead which is also interesting

p <- nrow(data$air)
n <- ncol(data$air)-1

resmat <- matrix(nrow=p,ncol=2)
tvseq <- sort(unique(c(seq(0,1,by=0.01),seq(0,0.1,by=0.001),seq(0,0.2,by=0.005),c(0,0.0001,0.001,0.002,0.005,0.01,0.015,0.02))))

for (k in sample(1:p,p)){
    X <- apply(cbind( data$air[k,], data$mslp[k,], data$prate[k,], data$shum[k,]),2,diff)

    train <- (round(n/4):round(n*3/4)) ## mid-block for training; can change
    test <- (1:n)[-train]
    ## can also space out by
    ## test <- test[seq(1,length(test),by=3)] to reduce autocorrelation
    Y <- as.factor((1:n)>round(n/2))
    rf <- randomForest(X[train,],Y[train])



    pred <- predict(rf, X[test,],type="prob")
    #conf <- table( Y[test], predict(rf,X[test,]))
    #hyper <- gethypertv(conf)
    hyper <- dWit( t=as.numeric(Y[test]), rho=-as.numeric(pred[,1]-pred[,2]),s=1.5, tv.seq  = tvseq, estimator.type = "binomial-test")$tvhat

    Yn <- as.numeric(Y)
    ra <- order( dp <- (pred[,1]-pred[,2]))
    fpr <- cumsum(as.numeric(Yn[test]==1)[ ra])/sum( Yn[test]==1)
    tpr <- cumsum(as.numeric(Yn[test]!=1)[ ra])/sum( Yn[test]!=1)
    auc <- max(0.5,sum(tpr*diff(c(0,fpr))))
    tvhat <- dWit( t=as.numeric(Y[test]), rho=-as.numeric(pred[,1]-pred[,2]),s=1.5, tv.seq  = tvseq)$tvhat

    resmat[k,] <- c(hyper, tvhat)
}

pdf(file="results_differenced.pdf",width=12,height=6)
par(mfrow=c(1,3))
plot(resmat[1:k,1],resmat[1:k,2],xlab="TV-bound (conf table)",ylab="TV-bound")
abline(c(0,1))
image.plot( matrix( resmat[,1],nrow=72),axes=FALSE,main="TV-bound (conf table)")
image.plot( matrix( resmat[,2],nrow=72),axes=FALSE,main="TV-bound")
dev.off()



# problems to address
# - is the comparison between binomial and the confusion table test ok?
# - try the binomial test and see if we loose or win compared to the other tests
# - what about weak signal? i.e. small lower-bounds? multiple testing adjustments? Permutation-based test?
# - improve the plots by using the true geolocalizations
# - do the second type of analysis (reference location)
# - try to use different types of normalization (no normalization, difference normalization, rank normalization)
# - investigate witness summaries instead of tv
# --> objective of that is decide if climatic data can be the main line of the paper

# if not, then we need to find another dataset close to the simulations of Nicolai.




